spring:
  application.name: spring_multidb
  output.ansi.enabled: always
  jpa:
    show-sql: true  # simple stdout sql to console
    properties.hibernate:
      format_sql: true
      highlight_sql: true
      use_sql_comment: true
      jdbc.time_zone: Asia/Seoul
    hibernate.ddl-auto: validate
  datasource:
    primary:
      jdbc-url: jdbc:sqlite:./embedded.db
      driver-class-name: org.sqlite.JDBC
    secondary:
      jdbc-url: jdbc:postgresql://localhost:5432/secondary
      username: {DATABASE_USERNAME}
      password: {DATABASE_PASSWORD}
      driver-class-name: org.postgresql.Driver
  task.scheduling.pool.size: 4  # set thread pool size for running tasks in parallel
